---
- name: Install ansible-uri prereqs
  pip:
    name: httplib2
  when: github_username != "" and github_api_token != ""

- name: Generate SSH key if necessary
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
  when: github_username != "" and github_api_token != ""

- name: Add SSH key to Github
  uri:
    url: https://api.github.com/user/keys?access_token={{ github_api_token }}
    method: POST
    body:
      title: "{{ ansible_user_id }}@{{ ansible_hostname }}"
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    body_format: json
    status_code: 201
  when: github_username != "" and github_api_token != ""

- name: Authorize SSH keys from Github
  authorized_key:
    key: https://github.com/{{ github_username }}.keys
    user: "{{ ansible_user_id }}"
  when: github_username != "" and github_api_token != ""
